name: build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - v1
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Fmt check
        run: make fmt-check
      - name: Linter check
        run: make lint
      - name: Run terraform-fmt-check
        run: make terraform-fmt
      - name: Run terraform lint
        run: make terraform-lint
      - name: Run tests
        run: make test
